server:
    port: 8761

spring:
    application:
        name: SERVICE_REGISTRY

#disable as client

eureka:
    instance:
        hostname: localhost
    client:
        fetch-registry: false
        register-with-eureka: false



